const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const source = fs.readFileSync(path.join(__dirname, '..', 'pages', 'work', 'profile-time.vue'), 'utf8')

test('profile time page supports manage mode with live loading, expired prioritization, and delete', () => {
  assert.match(source, /import\s*\{\s*getChefTime,\s*deleteChefTime\s*\}\s*from\s*'@\/api\/cooking\/chef'/)
  assert.doesNotMatch(source, /已按过期优先排序/)
  assert.doesNotMatch(source, /可直接清理过期时间段/)
  assert.match(source, /mode:\s*'draft'/)
  assert.match(source, /focus:\s*''/)
  assert.match(source, /isManageMode\(\)\s*\{\s*return this\.mode === 'manage'/)
  assert.match(source, /onLoad\(options = \{\}\)\s*\{[\s\S]*this\.mode = options\.mode === 'manage' \? 'manage' : 'draft'/)
  assert.match(source, /return this\.isManageMode \? this\.loadManageTimes\(\) : this\.loadDraft\(\)/)
  assert.match(source, /getChefTime\(\{\}\)\.then/)
  assert.match(source, /isExpiredTime\(item\)/)
  assert.match(source, /if \(this\.isManageMode\) \{[\s\S]*const aExpired = this\.isExpiredTime\(a\)[\s\S]*const bExpired = this\.isExpiredTime\(b\)/)
  assert.match(source, /<text v-if="isExpiredTime\(item\)" class="time-expired-tag">/)
  assert.match(source, /<view class="time-actions">[\s\S]*<view v-if="!isManageMode \|\| isExpiredTime\(item\)" class="text-action danger" @tap\.stop="removeTime\(item\)">删除<\/view>/)
  assert.match(source, /if \(this\.isManageMode && !this\.isExpiredTime\(item\)\) return/)
  assert.match(source, /async removeTime\(item\)/)
  assert.match(source, /if \(this\.isManageMode && item\.timeId\) \{[\s\S]*this\.chefTimes = this\.chefTimes\.filter\(time => time\.localId !== item\.localId\)[\s\S]*await deleteChefTime\(item\.timeId\)[\s\S]*await this\.loadManageTimes\(\)/)
})
