const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const source = fs.readFileSync(path.join(__dirname, '..', 'pages', 'work', 'settlement.vue'), 'utf8')

test('settlement page renders a paged card list with pull-down refresh and load-more controls', () => {
  assert.match(source, /<picker[\s\S]*mode="date"[\s\S]*fields="month"[\s\S]*@change="onMonthChange"/)
  assert.match(source, /clearMonthFilter/)
  assert.match(source, /<scroll-view[\s\S]*refresher-enabled="true"[\s\S]*@refresherrefresh="onPullDownRefresh"/)
  assert.match(source, /v-for="item in settlementList"/)
  assert.match(source, /class="settlement-card"/)
  assert.match(source, /item\.month/)
  assert.match(source, /item\.completeCount/)
  assert.match(source, /item\.payableAmount/)
  assert.match(source, /item\.settlementStatus/)
  assert.match(source, /@click="goDetail\(item\)"/)
  assert.match(source, /loadNextPage/)
  assert.match(source, /scrolltolower/)
  assert.match(source, /uni\.navigateTo\(\{[\s\S]*url: '\/pages\/work\/settlement-detail\?id=' \+ item\.id \+ '&month=' \+ item\.month/)
  assert.doesNotMatch(source, /查看全部/)
  assert.doesNotMatch(source, /结算列表/)
  assert.doesNotMatch(source, /loadPrevPage/)
  assert.doesNotMatch(source, /loadMoreText/)
  assert.doesNotMatch(source, /class="pager"/)
  assert.doesNotMatch(source, /getChefOrderList/)
  assert.doesNotMatch(source, /settlementOrders/)
})

test('settlement page normalizes natural-month list payload fields from backend settlement records and current review statuses', () => {
  assert.match(source, /'settlementNo'/)
  assert.match(source, /'completedCount'/)
  assert.match(source, /'settlementStatusName'/)
  assert.match(source, /GENERATED/)
  assert.match(source, /REVIEWING/)
  assert.match(source, /CONFIRMED/)
  assert.match(source, /PAID/)
  assert.match(source, /return this\.queryMonth \|\| '月度结算'/)
  assert.match(source, /if \(\/\^\\d\{6\}\$\/\.test\(text\)\) return `\$\{text\.slice\(0, 4\)\}-\$\{text\.slice\(4, 6\)\}`/)
})
