const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const source = fs.readFileSync(path.join(__dirname, '..', 'pages', 'work', 'settlement.vue'), 'utf8')

test('settlement page renders a paged card list with pull-down refresh and load-more controls', () => {
  assert.match(source, /<picker[\s\S]*mode="date"[\s\S]*fields="month"[\s\S]*@change="onMonthChange"/)
  assert.match(source, /clearMonthFilter/)
  assert.match(source, /<scroll-view[\s\S]*refresher-enabled="true"[\s\S]*@refresherrefresh="onPullDownRefresh"/)
  assert.match(source, /v-for="item in settlementList"/)
  assert.match(source, /class="settlement-card"/)
  assert.match(source, /item\.month/)
  assert.match(source, /item\.completeCount/)
  assert.match(source, /item\.payableAmount/)
  assert.match(source, /item\.settlementStatus/)
  assert.match(source, /@click="goDetail\(item\)"/)
  assert.match(source, /loadNextPage/)
  assert.match(source, /scrolltolower/)
  assert.match(source, /uni\.navigateTo\(\{[\s\S]*url: '\/pages\/work\/settlement-detail\?id=' \+ item\.id \+ '&month=' \+ item\.month/)
  assert.doesNotMatch(source, /全部月份/)
  assert.doesNotMatch(source, /按月份查看结算记录/)
  assert.doesNotMatch(source, /第 1 页/)
  assert.doesNotMatch(source, /loadPrevPage/)
  assert.doesNotMatch(source, /loadMoreText/)
  assert.doesNotMatch(source, /class="pager"/)
  assert.doesNotMatch(source, /getChefOrderList/)
  assert.doesNotMatch(source, /settlementOrders/)
  assert.doesNotMatch(source, /订单明细/)
  assert.doesNotMatch(source, /扣款说明/)
})
